/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

interface SearchInputProps {
  label: string;
  placeholder: string;
}

const SearchInput: React.FC<SearchInputProps> = ({ label, placeholder }) => (
  <div className="flex flex-col">
    <div className="text-base font-semibold text-slate-700">{label}</div>
    <div className="flex gap-0 justify-center">
      <div className="flex-1 justify-center px-1.5 py-2 text-xs bg-white rounded-xl text-slate-700">
        {placeholder}
      </div>
      <div className="flex justify-center items-center px-3.5 py-1.5 rounded-none bg-slate-500">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/c5cbab256756c79607f5705ff2b1acc60324ba1db388156fa52768ebbe53a23b?apiKey=c782aff3c66f48acb425981b997feb10&"
          alt="Search icon"
          className="aspect-square fill-slate-500 w-[22px]"
        />
      </div>
    </div>
  </div>
);

interface SelectInputProps {
  label: string;
  placeholder: string;
}

const SelectInput: React.FC<SelectInputProps> = ({ label, placeholder }) => (
  <div className="flex flex-col">
    <div className="text-base font-semibold text-slate-700">{label}</div>
    <div className="flex gap-0 justify-center">
      <div className="flex flex-1 gap-2.5 justify-center px-1.5 py-2 text-xs bg-white rounded-xl text-slate-700">
        <div className="flex-1 my-auto">{placeholder}</div>
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/8838497a164e5dd7988219c153109db44a3bdb2bcfbef0272b5dbf7966b81c79?apiKey=c782aff3c66f48acb425981b997feb10&" alt="Dropdown arrow" className="shrink-0 w-6 aspect-square" />
      </div>
      <div className="flex justify-center items-center px-3.5 py-1.5 rounded-none bg-slate-500">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/0a1b7e8b8f485585cd568d6c22a4d2d484cb1d417dacbf9a9c254c5acb474188?apiKey=c782aff3c66f48acb425981b997feb10&"
          alt="Select icon"
          className="aspect-[0.96] fill-slate-500 w-[23px]"
        />
      </div>
    </div>
  </div>
);

interface TextInputProps {
  label: string;
  placeholder: string;
}

const TextInput: React.FC<TextInputProps> = ({ label, placeholder }) => (
  <div className="flex flex-col text-slate-700">
    <label htmlFor={label} className="text-base font-semibold">
      {label}
    </label>
    <input
      type="text"
      id={label}
      placeholder={placeholder}
      className="justify-center px-1.5 py-2 text-xs bg-white rounded-xl"
    />
  </div>
);

const MyComponent: React.FC = () => {
  return (
    <div className="flex flex-col flex-wrap content-start py-3 rounded-3xl bg-slate-300">
      <div className="flex flex-col px-3 w-full max-md:max-w-full">
        <div className="flex gap-5 justify-between items-start max-md:flex-wrap max-md:max-w-full">
          <SearchInput label="Search By Territory Name" placeholder="Search for territory name" />
          <SelectInput label="Select Territory Name" placeholder="Select territory name" />
          <TextInput label="State" placeholder="Enter state" />
        </div>
        <div className="flex gap-5 justify-between mt-4 max-md:flex-wrap max-md:max-w-full">
          <TextInput label="Country" placeholder="Select country" />
          <TextInput label="Territory Zip Code" placeholder="Enter territory zip code" />
          <div className="flex flex-col">
            <div className="text-base font-semibold text-slate-700">Discount Allowed</div>
            <div className="flex gap-1 justify-center whitespace-nowrap">
              <div className="flex-1 justify-center px-1.5 py-2 text-xs bg-white rounded-xl text-slate-700">
                0.0
              </div>
              <div className="my-auto text-sm text-black">%</div>
            </div>
          </div>
        </div>
        <div className="flex flex-col mt-4 max-w-full w-[253px]">
          <div className="text-base font-semibold text-slate-700">Status</div>
          <div className="flex gap-4 mt-2.5">
            <div className="flex gap-1.5">
              <div className="flex flex-col justify-center my-auto">
                <div className="shrink-0 w-3 h-3 bg-white rounded-full" />
              </div>
              <div className="text-base text-slate-700">Active</div>
            </div>
            <div className="flex gap-1.5">
              <div className="flex flex-col justify-center my-auto">
                <div className="shrink-0 w-3 h-3 bg-white rounded-full" />
              </div>
              <div className="text-base text-slate-700">Inactive</div>
            </div>
          </div>
        </div>
        <div className="mt-4 max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col max-md:gap-0">
            <div className="flex flex-col w-[17%] max-md:ml-0 max-md:w-full">
              <div className="flex flex-col grow justify-center text-center">
                <div className="justify-center items-center px-16 py-6 text-base font-medium text-white rounded-3xl border border-solid bg-slate-700 border-slate-500 max-md:px-5">
                  Line No.
                </div>
                <div className="justify-center items-center px-16 py-6 text-sm whitespace-nowrap bg-white rounded-none border border-solid border-slate-500 text-slate-500 max-md:px-5">
                  1.
                </div>
              </div>
            </div>
            <div className="flex flex-col ml-5 w-[58%] max-md:ml-0 max-md:w-full">
              <div className="flex flex-col grow justify-center text-center max-md:max-w-full">
                <div className="justify-center items-center px-16 py-6 text-base font-medium text-white whitespace-nowrap border border-solid bg-slate-700 border-slate-500 max-md:px-5 max-md:max-w-full">
                  Sub-Territory
                </div>
                <div className="justify-center items-center px-16 py-6 text-sm bg-white border border-solid border-slate-500 text-slate-500 max-md:px-5 max-md:max-w-full">
                  No Record Available{" "}
                </div>
              </div>
            </div>
            <div className="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full">
              <div className="flex flex-col grow justify-center">
                <div className="justify-center px-12 py-6 text-base font-medium text-center text-white rounded-none border border-solid bg-slate-700 border-slate-500 max-md:px-5">
                  Remove Sub-Territory
                </div>
                <div className="flex justify-center items-center px-16 py-4 bg-white rounded-none border border-solid border-slate-500 max-md:px-5">
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/ba6e266cf733b59a1f8b5c5ea3609594435eedfd915ff2a082563a1e58e8632a?apiKey=c782aff3c66f48acb425981b997feb10&"
                    alt="Remove icon"
                    className="border-2 border-solid aspect-[0.81] border-slate-500 stroke-[2px] stroke-slate-500 w-[22px]"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <button className="justify-center self-end px-12 py-1 mt-4 mr-7 text-base font-semibold text-center text-white whitespace-nowrap rounded-xl bg-slate-700 max-md:px-5 max-md:mr-2.5">
        Save
      </button>
    </div>
  );
};

export default MyComponent;